/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/creation_opc` | `/creation_opc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LOCALIP` | `/LOCALIP`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcoes` | `/opcoes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/creation_opc` | `/creation_opc`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LOCALIP` | `/LOCALIP`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/opcoes` | `/opcoes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/creation_opc${`?${string}` | `#${string}` | ''}` | `/creation_opc${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LOCALIP${`?${string}` | `#${string}` | ''}` | `/LOCALIP${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/logs${`?${string}` | `#${string}` | ''}` | `/logs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/opcoes${`?${string}` | `#${string}` | ''}` | `/opcoes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/creation_opc` | `/creation_opc`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LOCALIP` | `/LOCALIP`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logs` | `/logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/opcoes` | `/opcoes`; params?: Router.UnknownInputParams; };
    }
  }
}
